language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - a.torrecilla@alumnos.upm.es
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

- mvn sonar:sonar \
  -Dsonar.projectKey=test:torrecilla \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.organization=agustinvalls-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=testTorrecilla